"""add contestant is_winner, drop week winner_id

Revision ID: d71d568fa540
Revises: c4c915815868
Create Date: 2026-07-09 10:51:01.507838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71d568fa540'
down_revision = 'c4c915815868'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('contestants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_winner', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # Preserve existing data: weeks.winner_id only ever supported a single
    # winner, so before it's dropped, carry that same contestant forward as
    # is_winner=True — the new column is a strict superset (it can also
    # represent ties, which the old column structurally couldn't).
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "UPDATE contestants SET is_winner = :val "
            "WHERE id IN (SELECT winner_id FROM weeks WHERE winner_id IS NOT NULL)"
        ),
        {"val": True},
    )

    # Don't assume the FK constraint is actually named (or even present)
    # exactly as the model declared — checked against a real deployment and
    # found weeks.winner_id had no FK constraint at all despite the model
    # saying otherwise, so ask the database what's really there instead of
    # guessing and having this migration fail on environments where the
    # constraint doesn't exist under that assumed name.
    inspector = sa.inspect(connection)
    existing_fk_names = {fk["name"] for fk in inspector.get_foreign_keys("weeks")}

    with op.batch_alter_table('weeks', schema=None) as batch_op:
        if "fk_week_winner" in existing_fk_names:
            batch_op.drop_constraint("fk_week_winner", type_="foreignkey")
        batch_op.drop_column('winner_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_week_winner'), 'contestants', ['winner_id'], ['id'])

    with op.batch_alter_table('contestants', schema=None) as batch_op:
        batch_op.drop_column('is_winner')

    # ### end Alembic commands ###
